name: Workflows secrets

on:
  schedule:
    - cron: '10 0 * * *'

jobs:
  my-job:
    name: Read Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          save-if: ${{ github.event_name == 'push'}}

      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - name: Test printing your secret of json
        run: cat $HOME/target/test/auth.json
      - name: Test printing your secret of toml
        run: cat $HOME/target/test/auth_toml.toml
      - name: Set file path in env
        run: echo "MY_FILE_PATH=$HOME/target/test/auth_toml.toml" >> $GITHUB_ENV
      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-image: redis/redis-stack-server
          redis-version: ${{ matrix.redis-version }
      - name: Execute tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
