name: Workflows secrets

on:
  push:

jobs:
  # Label of the container job
  my-job:

    name: Read Secrets
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          save-if: ${{ github.event_name == 'push'}}

      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      
      - name: Test printing your secret of json
        run: cat $HOME/target/test/auth.json
      
      - name: Test printing your secret of toml
        run: cat $HOME/target/test/auth_toml.toml
      
      - name: Set file path in env
        run: echo "MY_FILE_PATH=$HOME/target/test/auth_toml.toml" >> $GITHUB_ENV
      
      - name: Execute tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
